language: generic 
sudo: required 
services:
    - docker 

before_install:
    - docker build -t loesakb/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true loesakb/docker-react npm run test -- --coverage