language: generic 
sudo: required 
services:
    - docker 

before_install:
    - docker build -t loesakb/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true loesakb/docker-react npm run test -- --coverage

deoloy:
    edge: true
    provider: elasticbeantalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    backet_name: "elasticbeanstalk-us-east-2-163853346091"
    backet_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
